---
dist: precise

os:
  - linux

language: go

branches:
  only:
    - main

go:
  - 1.15.x

before_install:
  - sudo apt-get -y install curl
  - make setup
addons:
  apt:
    update: true

script:
  - make lint
  - make test

notifications:
  email: SedovSG@yandex.ru
  on_success: never
  on_failure: always
